apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-java
spec:
  selector:
    matchLabels:
      app: demo-java
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-java
    spec:
      containers:
      - name: demo-java
        image: 100.100.0.13/app/demo-java:1.0
        imagePullPolicy: Always
        env:
        - name: APP_VERSION
          value: 'BUILD_NUMBER'
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3

---
apiVersion: v1
kind: Service
metadata:
    name: demo-java
    labels:
      name: demo-java
spec:
    type: NodePort
    ports:
    - name: tcp
      port: 8080
      nodePort: 30100
    selector:
      app: demo-java
