apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloword
spec:
  selector:
    matchLabels:
      app: helloword
  replicas: 1
  template:
    metadata:
      labels:
        app: helloword
    spec:
      containers:
      - name: helloword
        image: 100.100.0.10:30001/app/demo:1.0
        imagePullPolicy: Always
        env:
        - name: keyword
          value: 'BUILD_NUMBER'
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3

---
apiVersion: v1
kind: Service
metadata:
    name: helloword
    labels:
      name: helloword
spec:
    type: NodePort
    ports:
    - name: tcp
      port: 8080
      nodePort: 30100
    selector:
      name: helloword