version: '2'

services:
    jenkins:
        restart: always
        image: jenkins/jenkins:lts-alpine
        ports:
            - "8080:8080"
            - "50000:50000"
        volumes:
            - ./data:/var/jenkins_home