def label = "pipeline-worker"
podTemplate(label: label, cloud: 'kubernetes', 
  containers: [
    containerTemplate(name: 'jnlp',
      ttyEnabled: true,
      image: 'jenkins/jnlp-slave:alpine'),
    containerTemplate(name: 'maven',
      ttyEnabled: true,
      command: 'cat',
      image: '100.100.0.13/devops/maven:jdk8-alpine'),
  containerTemplate(name: 'docker',
      ttyEnabled: true,
      command: 'cat',
      image: 'docker:1.13.0')
  ],
  volumes: [
    hostPathVolume(hostPath: '/var/run/docker.sock', mountPath:'/var/run/docker.sock'),
    hostPathVolume(hostPath: '/etc/docker/daemon.json', mountPath:'/etc/docker/daemon.json')
  ]) {
    node(label) {

      stage('Preparation') {
        container('jnlp') {
          sh 'sleep 10'
          git 'https://github.com/flyinghawkren/devops-plat.git'
        }
      }

      stage('Build') {
        container('maven') {
          sh 'cd demo/java && mvn -Dmaven.test.skip=true clean package'
        }
      }
      
      stage('SonarCheck') {
        container('maven') {
          sh 'cd demo/java && mvn sonar:sonar -Dsonar.projectKey=java-web-test -Dsonar.host.url=http://100.100.0.13:9000 -Dsonar.login=50714ff191af11806fb9fc3c61117de1cf12dbf3'
        }
      }

      stage('UnitTest') {
        container('maven') {
          sh 'cd demo/java && mvn test'
        }
      }
    
    stage('BuildImage') {
        container('docker') {
          sh 'cd demo/java && docker build -t 100.100.0.13/app/demo:1.0 .'
          sh 'docker login -u admin -p Harbor12345 http://100.100.0.13'
      sh 'docker push 100.100.0.13/app/demo:1.0'
        }
      }
    }
  }