def label = "pipeline-worker"
podTemplate(label: label, cloud: 'kubernetes', 
  containers: [
    containerTemplate(name: 'jnlp',
      ttyEnabled: true,
      image: 'jenkins/jnlp-slave:alpine'),
    containerTemplate(name: 'jnlp-mvn',
      ttyEnabled: true,
      command: 'cat',
      image: '100.100.0.13/devops/jnlp:maven-3.5.2')
  ],
  volumes: [
    hostPathVolume(hostPath: '/var/run/docker.sock', mountPath:'/var/run/docker.sock'),
    hostPathVolume(hostPath: '/etc/docker/daemon.json', mountPath:'/etc/docker/daemon.json')
  ]) {
    node(label) {

      stage('Preparation') {
        container('jnlp') {
          git 'https://github.com/jglick/simple-maven-project-with-tests.git'
        }
      }

      stage('Build') {
        container('jnlp-mvn') {
          sh 'mvn -Dmaven.test.failure.ignore clean package'
        }
      }

      stage('SonarCheck') {
        container('jnlp-mvn') {
          sh 'mvn sonar:sonar -Dsonar.projectKey=java-web-test -Dsonar.host.url=http://100.100.0.13:9000 -Dsonar.login=50714ff191af11806fb9fc3c61117de1cf12dbf3'
        }
      }

      stage('Results') {
          junit '**/target/surefire-reports/TEST-*.xml'
          archiveArtifacts 'target/*.jar'
      }
    }
  }