apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-cpp
spec:
  selector:
    matchLabels:
      app: demo-cpp
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-cpp
    spec:
      containers:
      - name: demo-cpp
        image: 100.100.0.13/app/demo-cpp:1.0
        imagePullPolicy: Always
        env:
        - name: APP_VERSION
          value: 'BUILD_NUMBER'
        ports:
        - containerPort: 9080
        readinessProbe:
          httpGet:
            path: /
            port: 9080
          initialDelaySeconds: 3
          periodSeconds: 3

---
apiVersion: v1
kind: Service
metadata:
    name: demo-cpp
    labels:
      name: demo-cpp
spec:
    type: NodePort
    ports:
    - name: tcp
      port: 9080
      nodePort: 30101
    selector:
      app: demo-cpp
