apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
spec:
  selector:
    matchLabels:
      app: helloworld
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: 100.100.0.13/app/demo-cpp:1.0
        imagePullPolicy: Always
        env:
        - name: APP_VERSION
          value: 'BUILD_NUMBER'
        ports:
        - containerPort: 9080
        readinessProbe:
          httpGet:
            path: /
            port: 9080
          initialDelaySeconds: 3
          periodSeconds: 3

---
apiVersion: v1
kind: Service
metadata:
    name: helloworld
    labels:
      name: helloworld
spec:
    type: NodePort
    ports:
    - name: tcp
      port: 9080
      nodePort: 30101
    selector:
      app: helloworld
