def label = "pipeline-worker"
podTemplate(label: label, cloud: 'kubernetes', 
  containers: [
    containerTemplate(name: 'jnlp',
      ttyEnabled: true,
      image: 'jenkins/jnlp-slave:alpine'),
    containerTemplate(name: 'jmeter',
      ttyEnabled: true,
      image: 'justb4/jmeter:5.1.1',
      command: 'cat')
  ],
  volumes: [nfsVolume(mountPath: '/test/', readOnly: false, serverAddress: '100.100.0.10', serverPath: '/nfsdata/test')]
  ) {
    node(label) {
      stage('test') {
        container('jmeter') {
          sh 'rm -rf /test/report/* && jmeter -n -t /test/http.jmx -l /test/report/result.jtl -e -o /test/report'
          publishHTML([allowMissing: false, alwaysLinkToLastBuild: false, keepAll: true, reportDir: '/test/report', reportFiles: 'index.html', reportName: 'Jmeter Report', reportTitles: ''])
        }
      }
    }
  }